language: python
cache: pip
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - make bootstrap
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then travis_retry pip install pytest==2.9.1; fi

script: make
branches:
    except:
        - /^v[0-9]/
after_success: coveralls
